# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gismallclient' do
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gismallclient

  

  platform :ios, '13.0'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'


  target 'gismallclientTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'gismallclient-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gismallclient-tvOS

  target 'gismallclient-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
