export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILED = 'GET_USER_INFO_FAILED';
export const GET_USER_INFO_REQUESTED = 'GET_USER_INFO_REQUESTED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';
export const SIGN_OUT_REQUESTED = 'SIGN_OUT_REQUESTED';

export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAILED = 'ADD_CONTACT_FAILED';
export const ADD_CONTACT_REQUESTED = 'ADD_CONTACT_REQUESTED';

export const FETCH_CONTACT_LIST_SUCCESS = 'FETCH_CONTACT_LIST_SUCCESS';
export const FETCH_CONTACT_LIST_FAILED = 'FETCH_CONTACT_LIST_FAILED';
export const FETCH_CONTACT_LIST_REQUESTED = 'FETCH_CONTACT_LIST_REQUESTED';

export const FETCH_USER_LIST_SUCCESS = 'FETCH_USER_LIST_SUCCESS';
export const FETCH_USER_LIST_FAILED = 'FETCH_USER_LIST_FAILED';
export const FETCH_USER_LIST_REQUESTED = 'FETCH_USER_LIST_REQUESTED';

export const FETCH_MESSAGE_LIST_SUCCESS = 'FETCH_MESSAGE_LIST_SUCCESS';
export const FETCH_MESSAGE_LIST_FAILED = 'FETCH_MESSAGE_LIST_FAILED';
export const FETCH_MESSAGE_LIST_REQUESTED = 'FETCH_MESSAGE_LIST_REQUESTED';

export const ON_SEND_MESSAGE = 'ON_SEND_MESSAGE';
export const ON_RECEIVE_MESSAGE = 'ON_RECEIVE_MESSAGE';

export const SET_STATUS_BAR_COLOR = 'SET_STATUS_BAR_COLOR';
export const SET_STATUS_BAR_STYLE = 'SET_STATUS_BAR_STYLE';

export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_REQUESTED = 'FETCH_MESSAGES_REQUESTED';
export const FETCH_MESSAGES_FAILED = 'FETCH_MESSAGES_FAILED';

export const REGISTER_REQUESTES = 'REGISTER_REQUESTES';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
